# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tjerome-rocher/Desktop/tek3/R-Type

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tjerome-rocher/Desktop/tek3/R-Type

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tjerome-rocher/Desktop/tek3/R-Type/CMakeFiles /home/tjerome-rocher/Desktop/tek3/R-Type//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tjerome-rocher/Desktop/tek3/R-Type/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named component_position2D

# Build rule for target.
component_position2D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 component_position2D
.PHONY : component_position2D

# fast build rule for target.
component_position2D/fast:
	$(MAKE) $(MAKESILENT) -f R-TypeGame/components/CMakeFiles/component_position2D.dir/build.make R-TypeGame/components/CMakeFiles/component_position2D.dir/build
.PHONY : component_position2D/fast

#=============================================================================
# Target rules for targets named component_position3D

# Build rule for target.
component_position3D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 component_position3D
.PHONY : component_position3D

# fast build rule for target.
component_position3D/fast:
	$(MAKE) $(MAKESILENT) -f R-TypeGame/components/CMakeFiles/component_position3D.dir/build.make R-TypeGame/components/CMakeFiles/component_position3D.dir/build
.PHONY : component_position3D/fast

#=============================================================================
# Target rules for targets named r-type_ecs

# Build rule for target.
r-type_ecs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_ecs
.PHONY : r-type_ecs

# fast build rule for target.
r-type_ecs/fast:
	$(MAKE) $(MAKESILENT) -f Ecs/CMakeFiles/r-type_ecs.dir/build.make Ecs/CMakeFiles/r-type_ecs.dir/build
.PHONY : r-type_ecs/fast

#=============================================================================
# Target rules for targets named r-type_server

# Build rule for target.
r-type_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_server
.PHONY : r-type_server

# fast build rule for target.
r-type_server/fast:
	$(MAKE) $(MAKESILENT) -f Server/CMakeFiles/r-type_server.dir/build.make Server/CMakeFiles/r-type_server.dir/build
.PHONY : r-type_server/fast

#=============================================================================
# Target rules for targets named r-type_client

# Build rule for target.
r-type_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_client
.PHONY : r-type_client

# fast build rule for target.
r-type_client/fast:
	$(MAKE) $(MAKESILENT) -f Client/CMakeFiles/r-type_client.dir/build.make Client/CMakeFiles/r-type_client.dir/build
.PHONY : r-type_client/fast

#=============================================================================
# Target rules for targets named sever_test

# Build rule for target.
sever_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sever_test
.PHONY : sever_test

# fast build rule for target.
sever_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/sever_test.dir/build.make tests/CMakeFiles/sever_test.dir/build
.PHONY : sever_test/fast

#=============================================================================
# Target rules for targets named client_test

# Build rule for target.
client_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_test
.PHONY : client_test

# fast build rule for target.
client_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/client_test.dir/build.make tests/CMakeFiles/client_test.dir/build
.PHONY : client_test/fast

#=============================================================================
# Target rules for targets named ecs_test

# Build rule for target.
ecs_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecs_test
.PHONY : ecs_test

# fast build rule for target.
ecs_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ecs_test.dir/build.make tests/CMakeFiles/ecs_test.dir/build
.PHONY : ecs_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client_test"
	@echo "... component_position2D"
	@echo "... component_position3D"
	@echo "... ecs_test"
	@echo "... r-type_client"
	@echo "... r-type_ecs"
	@echo "... r-type_server"
	@echo "... sever_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

