name: cmake
on: [check_run, pull_request]
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, windows-latest]

    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: Install dependencies on Windows (vcpkg)
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install
          apt install ninja-build

      - name: build project Windows
        if: matrix.os == 'windows-latest'
        uses: threeal/cmake-action@v2.0.0
        with:
          options: |
            CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
            BUILD_TESTS=OFF
            BUILD_EXAMPLES=ON
          build-dir: build

      - name: Install dependencies on Ubuntu (vcpkg)
        if: matrix.os == 'ubuntu-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install

      - name: build project Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: threeal/cmake-action@v2.0.0
        with:
          options: |
            CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
            BUILD_TESTS=OFF
            BUILD_EXAMPLES=ON
          build-dir: build