name: cmake
on: [check_run, pull_request]
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: Set up vcpkg
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v5
        with:
          install: true

      # Install Criterion
      - name: Install Criterion
        if: matrix.os == 'windows-latest'
        run: |
          .\vcpkg\vcpkg.exe install criterion

      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libcriterion-dev

      - name: build project
        uses: threeal/cmake-action@v2.0.0
