name: Generate Doxygen Documentation and Readme

on:
  push:

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Doxygen
        run: sudo apt-get install -y doxygen graphviz  # Graphviz is required for generating diagrams

      - name: Generate Doxygen Documentation
        run: |
          cd Docs
          doxygen Doxyfile

      - name: Clone GitHub Wiki
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Wiki Documentation
        run: |
          # Delete the old documentation
          rm -rf wiki/docs
          mkdir -p wiki/docs
          cp -r Docs/doxygen/html/ wiki/docs

          # Commit and push the changes
          cd wiki
          git add .
          git commit -m "Update Doxygen documentation"
          git push

      - name: Update README.md
        run: |
          cp README.md wiki/readme.md
          cd wiki
          git add readme.md
          git commit -m "Update README.md"
          git push
