name: Generate Doxygen Documentation and Readme

on:
  push:

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Doxygen
        run: sudo apt-get install -y doxygen graphviz  # Graphviz is required for generating diagrams

      - name: Generate Doxygen Documentation
        run: |
          cd Docs
          doxygen Doxyfile
          cd ..

      - name: Clone GitHub Wiki
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}

      - name: Update Wiki Documentation
        run: |
          # Delete the old documentation
          rm -rf wiki/docs
          mkdir -p wiki/docs
          cp -r Docs/doxygen/html/* wiki/docs

          # Commit and push the changes
          cd wiki
          git add .
          git commit -m "Update Doxygen documentation"
          git push

          # Update the README.md
          rm -rf readme.md
          cp ../README.md readme.md
          git add .
          git commit -m "Update README.md"
          git push
