name: Linux
on:
  check_run:
  pull_request:
  workflow_dispatch:

jobs:
  cmake-build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: vcpkg
          key: vcpkg-cache-${{ runner.os }}

      - name: Apt install for Ubuntu
        run: |
          sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

      - name: Install dependencies on Ubuntu (vcpkg)
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh
          fi
          ./vcpkg/vcpkg install

      - name: Build project
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build/ --config Debug

      - name: Run tests
        run: |
          cd build/tests/
          ctest -C Debug

      - name: Upload Executables as Artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v3
        with:
          name: Game_Folder_Linux
          path: ./Game/
