name: release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
  schedule:
    - cron: '0 18 * * 5'  # Runs every Friday at 6pm UTC

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ./artifacts

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: v0.${{ github.run_number }} | Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/r-type_client-ubuntu-latest
          asset_name: r-type_client-ubuntu-latest
          asset_content_type: application/octet-stream

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/r-type_client-windows-latest
          asset_name: r-type_client-windows-latest
          asset_content_type: application/octet-stream

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/r-type_server-ubuntu-latest
          asset_name: r-type_server-ubuntu-latest
          asset_content_type: application/octet-stream

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/r-type_server-windows-latest
          asset_name: r-type_server-windows-latest
          asset_content_type: application/octet-stream

