name: tests_check
on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasio-dev

      - name: Build project
        uses: threeal/cmake-action@v2.0.0
        with:
          directory: .
          build-directory: build
          options: '-DCMAKE_BUILD_TYPE=Release'

      - name: Run tests with ctest
        run: |
          cd build/tests/
          ctest
