name: Windows
on:
  check_run:
  pull_request:
  workflow_dispatch:

jobs:
  cmake-build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: vcpkg
          key: vcpkg-cache-${{ runner.os }}

      - name: Install dependencies on Windows (vcpkg)
        shell: pwsh
        run: |
          if (-Not (Test-Path "vcpkg")) {
            git clone https://github.com/microsoft/vcpkg.git
            .\vcpkg\bootstrap-vcpkg.bat
          }
          .\vcpkg\vcpkg install

      - name: Build project
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build/ --config Debug

      - name: Run tests
        run: |
          cd build/tests/
          ctest -C Debug

      - name: Rename Executables
        if: github.event_name == 'workflow_dispatch'
        run: |
         cp -r Game/ Game_Windows/
         ls Game_Windows/
         echo "Windows Executables renamed"

      - name: Upload Executables as Artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v3
        with:
          name: Game_Windows
          path: ${{ github.workspace }}/Game_Windows/
